config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes, only: %i[index show]
  match '*path', to: 'recipes#index', via: :all
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
# frozen_string_literal: true

class Chef < ApplicationRecord
  has_many :recipes
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  belongs_to :chef, optional: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  include ApplicationHelper
  before_action :set_recipes, only: %i[index]
  around_action :catch_not_found
  before_action :set_recipe, only: %i[show]

  def index
    @recipes = Recipe.all
  end

  def show; end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_recipes
    recipe_fields_collection = contentful.entries(content_type: 'recipe').map(&:fields)
    load_or_create(recipe_fields_collection)
  end

  def load_or_create(recipe_fields_collection)
    recipe_fields_collection.each do |fields_collection|
      RecipeBuilder.new(fields_collection).perform
    end
  end

  def catch_not_found
    yield
  rescue ActiveRecord::RecordNotFound
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def contentful
    @contentful ||= Contentful::Client.new(
      access_token: ENV['CONTENTFUL_ACCESS_TOKEN'],
      space: ENV['CONTENTFUL_SPACE_ID'],
      dynamic_entries: :auto,
      raise_errors: true
    )
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RecipeApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/recipes/index.html.haml
- @recipes.each do |recipe|
  %p
  %h2{:style => "text-align:center"}= recipe.title
  %p
    = link_to image_tag(recipe.image_url, alt: recipe.title, style: 'display: block; margin: auto; width: 40%; padding-bottom: 50px;'), recipe

app/views/recipes/show.html.haml
%p
%h1{:style => "text-align:center"}= @recipe.title
%p
  = image_tag(@recipe.image_url, alt: @recipe.title, style: 'display: block; margin: auto; width: 60%')
- if @recipe.tags
  %p
    %strong Tags:
    = @recipe.tags.join(', ')
%p
  = @recipe.description
  - if @recipe.chef
    %p
      %strong Chef:
      = @recipe.chef.name

= link_to 'Back', recipes_path